### ISSUE TITLE
Add JSON.stringify() possibility in readme

### ISSUE THREAD

**Issue by xmik** [8bitDesigner/tp-api#3]
First, thank you for `tp-api`. The code still works, I'd just like to suggest adding one note to readme. 

Using a very similar example to the one from readme:

``` javascript
tp('Tasks')
  .take(1)
  .where("EntityState.Name eq 'Open'")
  .pluck("CustomFields")
  .sortBy('NumericPriority')
  .then(function(err, tasks) {
    console.log('my tasks', tasks)
  }
)
```

The returned `tasks` here is a JavaScript object which can return:

``` bash
my tasks [ { ResourceType: 'Task',
    Id: 3631,
    Project: { ResourceType: 'Project', Id: 4026, Process: [Object] },
    CustomFields: [ [Object], [Object], [Object], [Object], [Object] ] } ]
```

In order to convert it into JSON string, the following is enough:

``` javascript
tp('Tasks')
  .take(1)
  .where("EntityState.Name eq 'Open'")
  .pluck("CustomFields")
  .sortBy('NumericPriority')
  .then(function(err, tasks) {
    console.log('my tasks', JSON.stringify(tasks))  // changed here
  }
)
```

and now it returns:

``` bash
my tasks [{"ResourceType":"Task","Id":3631,"Project":{"ResourceType":"Project","Id":4026,"Process":{"Id":5,"Name":"AIScrum"}},"CustomFields":[{"Name":"Component","Type":"DropDown","Value":null},{"Name":"trac","Type":"Number","Value":null},{"Name":"Job","Type":"DropDown","Value":null},{"Name":"Resolution","Type":"DropDown","Value":null},{"Name":"Domain","Type":"DropDown","Value":null}]}]
```

It took me some time to find out about it, so I'd like to spare this time for others.

**Comment by 8bitDesigner** [comment]
Good call; I'll be honest and say that we've moved to using Jira at Fullscreen, so I don't have any way to confirm or test this. Can I give you contributor permissions so you can commit this change directly to the repo?

**Comment by xmik** [comment]
That would be ok. I also have 2 new methods to add (to append fields and sort in descending order described on [dev.targetprocess.com](http://dev.targetprocess.com/rest/response_format)). But I have to admit, I don't have a lot of experience with JavaScript.

**Comment by 8bitDesigner** [comment]
Well, you have commit access. Feel free to open a pull request and ping me if you need a second set of eyes, or a hand walking through my terrible, terrible code.

**Comment by xmik** [comment]
Thanks

**Comment by mathiasschopmans** [comment]
@xmik The _problem_ is related to `console.log` as it's not printing all levels of the object.

I prefer to use node's [`util.inspect`](https://nodejs.org/api/util.html#util_util_inspect_object_options) to inspect variables, as you do have more fine-grained control. :)

```
const util = require('util');
console.log(util.inspect(YOUR_OBJECT, { showHidden: true, depth: null }));
```

From the docs:

> The util.inspect() method returns a string representation of object that is primarily useful for debugging. Additional options may be passed that alter certain aspects of the formatted string.

So this can be easily adapted to your example:

```
var util = require('util');
tp('Tasks')
  .take(1)
  .where("EntityState.Name eq 'Open'")
  .pluck("CustomFields")
  .sortBy('NumericPriority')
  .then(function(err, tasks) {
    console.log(util.inspect(tasks, { showHidden: true, depth: null }));
  }
)
```
