### ISSUE TITLE
Release 1.0.6

### ISSUE THREAD

**Issue by xmik** [8bitDesigner/tp-api#6]
@8bitDesigner , could you release current master as 1.0.6 so that `npm install tp-api` installs 1.0.6?

---

Update: or maybe I can release it?

**Comment by 8bitDesigner** [comment]
Done! And if you hit me back with your username on NPM, I'll add you as a collaborator so you can publish new versions in the future! :)

**Comment by xmik** [comment]
Great. :) I am now xmik on NPM too.

**Comment by 8bitDesigner** [comment]
Great, you're added!
